USE MOLC;


DROP TABLE RAPORTY;
DROP TABLE LOGI;
DROP TABLE SAMOLOTY;
DROP TABLE PRODUCENCI;
DROP TABLE ZAMOWIENIA;
DROP TABLE FIRMY_LOGISTYCZNE;
DROP TABLE HANGARY;
DROP TABLE PRACOWNIK_SAMOLOTU;
DROP TABLE DZIALY;
DROP TABLE LINIE_LOTNICZE;